### ISSUE TITLE
DEXseq with more than two groups/conditions.

### ISSUE THREAD

**Issue by callumparr** [areyesq89/DEXSeq#17]
I am wanting to run a DTU analysis on a differentiation series with three samples iPSC, NSC, and Neuron. I know I can run DEXseq in parallel for each of the three possible pairwise combinations but to make life easiere I just wanted to input everything at once into a DEXseq object and then use something similar like contrasts that is used with DEseq2 to extract the DTU between each of the comparisons. 

Is this possible? How would one extract the dxr results for each of the comparisons?

**Comment by ThuyTien1** [comment]
Hi @callumparr , may I ask which version of R and DEXseq are you using? I'm trying to use DEXseq but get stuck at dispersion estimation step.

**Comment by callumparr** [comment]
I was running R 4.2 and the latest DEXseq available from Bioconductor.

I think you can follow the vignette to get some idea of why it is not working. 

Try explicitly calling the function, that is DEXseq::function() rather than function(). If you have multiple libraries loaded into your environment there maybe be some ambiguous naming going  on.

**Comment by areyesq89** [comment]
I've noticed a similar behavior as well, particularly when using multiple cores via `BPPARAM=MulticoreParam()`. For me, it turned out that BLAS was configured to use 4 CPUs by default. For a reason I do not understand this was making DEXSeq to stall, and it is fixed by decreasing the number of CPUs used by BLAS using environment variables. 

```
export OMP_NUM_THREADS=1 OPENBLAS_NUM_THREADS=1 MKL_NUM_THREADS=1
```

Would that maybe help?
